### ISSUE TITLE
Cannot Access the Dataset

### ISSUE THREAD

**Issue by HRHLALALA** [SPALaboratory/SiT-Dataset#3]
Hi, it seems that the full dataset is released but I cannot access the folder. May I ask when it will fully open to public?

<img width="798" alt="image" src="https://github.com/SPALaboratory/SiT-Dataset/assets/32263355/fe9b7b9b-ef6a-4853-b4ee-65eb5667d695">

**Comment by murraiya** [comment]
Same here. Plz open to public.

**Comment by SPALaboratory** [comment]
We apologize for the delay in our process. 
We have uploaded the document to Google Drive, but we are currently conducting a final review regarding the terms of the agreement before making it publicly available. 
We assure you that access will be granted by the end of this week or next week.

Thank you for your patience and interest.

**Comment by SPALaboratory** [comment]
The final version is now live. Plz Fill out our google form to get a download link.

**Comment by HRHLALALA** [comment]
> The final version is now live. Plz Fill out our google form to get a download link.

Hi, thanks for the releasing. However, I can still not access the form. Can you double check it? Thanks.

<img width="654" alt="image" src="https://github.com/SPALaboratory/SiT-Dataset/assets/32263355/49a56258-0281-4c36-85b8-76bf728bc7e7">

**Comment by SPA-junghokim** [comment]
I wanted to ask if the issue you're experiencing also occurs when accessing the form via the confirmation link after completing it. We tested it on our end, and everything seemed to work fine, so we wanted to confirm.

Thank you for your cooperation.

**Comment by JJYSTEM** [comment]
> > The final version is now live. Plz Fill out our google form to get a download link.
> 
> Hi, thanks for the releasing. However, I can still not access the form. Can you double check it? Thanks.
> 
> <img alt="image" width="654" src="https://private-user-images.githubusercontent.com/32263355/342618681-49a56258-0281-4c36-85b8-76bf728bc7e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzg5MTksIm5iZiI6MTczNDMzODYxOSwicGF0aCI6Ii8zMjI2MzM1NS8zNDI2MTg2ODEtNDlhNTYyNTgtMDI4MS00YzM2LTg1YjgtNzZiZjcyOGJjN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA4NDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YjVjYmNiNGQ2MjJjODgyZDRlNTA0NzQwYjNkNzZjZTk5YzBlZmZhNGIzOTc4MjZmMTgwNjRhYzJmMjczZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hTzqeXJmhelPSbYN8tGtrtInAZnmOdhCl-ZobnmuU80">

Hi, thank you for the great work! I have requested for data access through Google Form one week ago, and would be nice if I can access faster

**Comment by SPALaboratory** [comment]
You can see the download link in final page of google form.

Thank you for your attention to our dataset.
