### ISSUE TITLE
Developing tools to visualize the data 

### ISSUE THREAD

**Issue by hutslib** [SPALaboratory/SiT-Dataset#4]
Hi, great work!
Would you release some developing tools to visualize the data and the provided ground truth?
Or some documents to explain the dataset structure?
Waiting for your reply!

**Comment by SPALaboratory** [comment]
Thanks for your interest.
I am currently preparing to upload the training code for the detection/trajectory prediction model and will do so within the next week. 
I will provide the visualization code and data structure along with the training code upload. 

Thank you.

**Comment by SPALaboratory** [comment]
We have added the visualization code on top of the FCOS3D code. 
Please refer to the code below, and let us know if you have any questions after reviewing it.

[FCOS3D page](https://github.com/SPALaboratory/SiT-Dataset/tree/main/detection/FCOS3D)
```
python visualize_3dbox_on_image.py
```
