### ISSUE TITLE
Release the Preprocessed Trajectory files

### ISSUE THREAD

**Issue by HRHLALALA** [SPALaboratory/SiT-Dataset#5]
Hi, the full dataset is too large to be downloaded. Is it possible to release the preprocessed trajectory files such as ``trajectory_txt", train.pkl, val.pkl and test.pkl?

ynet
├── data
│   ├── semantic_maps_json
│   ├── semantic_map
│   ├── trajectory_txt
│   ├── tran.pkl
│   ├── val.pkl
│   ├── test.pkl

**Comment by HRHLALALA** [comment]
I am trying to generate the preprocessed dataset for YNet but failed. I have run into the following problems:

* I cannot find the `./SiT_dataset/first_loc`  at https://github.com/SPALaboratory/SiT-Dataset/blob/1409c5cd98ab872a5a7223ee7b5abed17173aa05/prediction/ynet/preprocess_ped.py#L205. 
* Even I comment the code and successfully generate the pickle files, the coordinates do not match the segmentation maps. 
* I also tried to plot the locations in `label_3d` and draw the polygons in the json files in the folder `semantic-maps`. However, they are not matched as well. 

Would you please provide some details of the data format and data preprocessing? Really appreciate in advance.

**Comment by SPA-junghokim** [comment]
sorry to be late abour updaring code. i will upload as soon as possible for
ped prediction.

_______________________________________________________
Jungho, Kim
Ph.D. Candidate, Dept. of Artificial Intelligence, Hanyang University.

*Signal Processing & Artificial-intelligence Laboratory.*
Hanyang University Engineering Center Main Building 408-1
222 Wangsimni-ro, Seongdong-gu, Seoul 133791, Republic of Korea

E-mail  : ***@***.*** ***@***.***>

Mobile : +82 10-9852-6898
_______________________________________________________


2024년 8월 2일 (금) 18:08, HRHLALALA ***@***.***>님이 작성:

**Comment by Fujiry0** [comment]
I have the same problem.

**Comment by SPA-junghokim** [comment]
We apologize for the delay in responding. 
We needed some extra time to review and verify the code. 
Could you please check the newly uploaded Ynet code?

We will be re-uploading the NSP code shortly as well.

Thank you for your understanding.

**Comment by HRHLALALA** [comment]
> We apologize for the delay in responding. We needed some extra time to review and verify the code. Could you please check the newly uploaded Ynet code?
> 
> We will be re-uploading the NSP code shortly as well.
> 
> Thank you for your understanding.

Thank you for your update. I notice that Cafeteria_4 also does have the label_3d folder. Can you help check this? Thanks

**Comment by SPALaboratory** [comment]
The reason why the label_3d is missing for Cafeteria_4 is that this scene is part of the test set. 
Similarly, other scenes that belong to the test set do not have label_3d either.

**Comment by HRHLALALA** [comment]
> The reason why the label_3d is missing for Cafeteria_4 is that this scene is part of the test set. Similarly, other scenes that belong to the test set do not have label_3d either.

One main issue is that this could cause error when executing preprocess_ped.py.  Removing the test sets successfull generate the pandas files. The trajectories match the scene map very well. Thank you very much.

**Comment by SPALaboratory** [comment]
Thanks for checking the code and letting me know. Thanks to you, I've fixed the code.  
Regarding the test set, there are still some things to review, so it will take some more time.
