### ISSUE TITLE
Error in 2d bounding box annotation?

### ISSUE THREAD

**Issue by Jaewoo97** [SPALaboratory/SiT-Dataset#7]
Hello,

There are instances where more than two 2d bbox annotation camera IDs are present for a pedestrian. 

A pedestrian cannot be seen in more than two cameras due to field of view. However, for example in frame 7 of Cafe_street_2-001, there are three 2dbbox annotation for Pedestrian:1, being present in camera ID 2,3,4.

When looking at the images, 2,3 are the same person, but 4 is not Pedestrian:1. It would be great if you could fix this error.

Thanks for a great dataset!

**Comment by SPA-junghokim** [comment]
Thank you for your interest in the SiT dataset. 
We sincerely hope it will serve as a valuable resource for your future research.

Thanks to your work, we identified an issue with some annotations in the dataset. 
We appreciate your attention to detail and will review and address this issue as quickly as possible.

**Comment by SPALaboratory** [comment]
Dear @Jaewoo97 
Thank you for your interest in our dataset.
We've taken care of the label issue you sent us and updated our Google Drive. We would appreciate it if you could re-download Cafe_street_2.zip.

Thank you for your help in improving our dataset.
