### ISSUE TITLE
Lost data

### ISSUE THREAD

**Issue by r3krut** [SPALaboratory/SiT-Dataset#8]
Hi!
Thanks for the nice dataset!
I realized, that there are no some scenes in Three_way_Intersection, but in train.txt split they are(Three_way_Intersection_1).
![sit_dataset](https://github.com/user-attachments/assets/21fcce6e-3bc1-448e-8b8a-b5093ba53c45)
![sit_train_split](https://github.com/user-attachments/assets/af7bdfee-94cc-469f-8317-5475dffd6f92)

Where can I find them?
Thanks!

**Comment by SPA-junghokim** [comment]
Thank you very much for your interest in the SiT dataset and for conducting research using it.
We sincerely hope that this dataset will contribute to your future successful research.

We recently discovered a localization issue with the `Three_way_intersection_1` and `Three_way_intersection_2` sections and have consequently halted the distribution of these specific datasets. While we have removed the raw data, including images and point clouds, we missed removing the `train.txt` file used for the training split. This file has now been updated and re-uploaded to Google Drive.

Let me know if you have any questions.
